"""update product category to erp styles

Revision ID: 3076d51d119d
Revises: c90ee080f258
Create Date: 2026-01-03 20:47:49.352135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3076d51d119d'
down_revision: Union[str, Sequence[str], None] = 'c90ee080f258'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    # ========= CATEGORY =========
    op.add_column(
        'categories',
        sa.Column('is_active', sa.Boolean(), server_default='true')
    )
    op.add_column('categories', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column(
        'categories',
        sa.Column('created_at', sa.DateTime(), server_default=sa.func.now())
    )
    op.add_column(
        'categories',
        sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now())
    )

    op.alter_column(
        'categories', 'name',
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=255),
        existing_nullable=False
    )

    op.alter_column( 
        'categories', 'description',
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=500),
        existing_nullable=True
    )

    op.add_column(
        'products',
        sa.Column('sku', sa.String(length=100), nullable=True)
    )

    op.add_column('products', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column(
        'products',
        sa.Column('is_active', sa.Boolean(), server_default='true')
    )
    op.add_column('products', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column(
        'products',
        sa.Column('created_at', sa.DateTime(), server_default=sa.func.now())
    )
    op.add_column(
        'products',
        sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now())
    )

    op.execute("""
        UPDATE products
        SET sku = code
        WHERE sku IS NULL
    """)

    op.alter_column(
        'products',
        'sku',
        nullable=False
    )

    op.drop_index(op.f('ix_products_code'), table_name='products')
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)

    op.drop_column('products', 'stock')
    op.drop_column('products', 'code')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('stock', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.create_index(op.f('ix_products_code'), 'products', ['code'], unique=True)
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'created_at')
    op.drop_column('products', 'deleted_at')
    op.drop_column('products', 'is_active')
    op.drop_column('products', 'description')
    op.drop_column('products', 'sku')
    op.alter_column('categories', 'description',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('categories', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('categories', 'updated_at')
    op.drop_column('categories', 'created_at')
    op.drop_column('categories', 'deleted_at')
    op.drop_column('categories', 'is_active')
    # ### end Alembic commands ###
